apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: notification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: your-dockerhub-username/notification-service:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: notification
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
